version: "3.5"

services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: "secretboard"

  web:
    build: ./web
    command: ./wait-for-it.sh -t 5 db:5432 -- sh -c "python manage.py migrate && gunicorn -b 0.0.0.0:8000 -w 4 secretboard.wsgi"
    environment:
      SB_DB_HOST: db
      SB_DB_NAME: "secretboard"
      SB_DB_USER: "secretboard"
    volumes:
      - static_files:/static_files
    depends_on:
      - db

  nginx:
    build: ./nginx
    volumes:
      - static_files:/static_files
    depends_on:
      - web

volumes:
  static_files:
